version: "3.7"

services:
  node:
    container_name: node
    image: node:latest
    ports:
      - 8081:8081
    working_dir: /node
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mlp1234
      MYSQL_DB: filmes

  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - filmes-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mlp1234
      MYSQL_DATABASE: filmes

volumes:
  filmes-mysql-data:

networks:
  filmes: