version: "3"

services:
  node:
    container_name: node
    image: node:latest
    command: npm start
    ports:
      - 8080:8080
    working_dir: /DW1
    volumes:
      - ./:/DW1
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mlp1234
      MYSQL_DB: filmes

  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - filmes-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mlp1234
      MYSQL_DATABASE: filmes

volumes:
  filmes-mysql-data:
